export const REQUEST_POKEMON_PENDING = 'REQUEST_POKEMON_PENDING';
export const REQUEST_POKEMON_SUCCESS = 'REQUEST_POKEMON_SUCCESS';
export const REQUEST_POKEMON_FAILED = 'REQUEST_POKEMON_FAILED';
export const CHANGE_ROWS_PER_PAGE = 'CHANGE_ROWS_PER_PAGE';
export const SORT_BY_VALUE = 'SORT_BY_VALUE';
